global-search add pinyin-pro history collect
soybeanjs/soybean-admin pull request #585
Opened 2024-08-06 06:18 UTC by sakanaovo

## 功能新增
1. 添加 `pinyin-pro` 支持拼音搜索查询路由
2. 搜索路由支持历史和收藏功能

2024-08-06 06:22 UTC, Azir-11 requested changes

2024-08-06 06:22 UTC, Azir-11 commented on src/layouts/modules/global-search/components/search-history.vue
没有适配i18n

2024-08-06 06:29 UTC, sakanaovo commented on src/layouts/modules/global-search/components/search-history.vue
应该放在 locales/langs/zh-ch common 对象下么

2024-08-06 06:37 UTC, honghuangdc commented
粗略地看了一下，代码好像没有格式化，写的质量有待提高，暂时先不合并，等有空我再好好评一下

2024-09-05 00:00 UTC, honghuangdc commented
不过目前 SoybeanAdmin 打算处于维护bug阶段，暂时不做功能上的变更

2024-09-05 00:00 UTC, closed without merging